#铜矿石

execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~-1 ~-1 copper_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~-1 ~0 copper_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~-1 ~1 copper_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~0 ~-1 copper_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~0 ~0 copper_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~0 ~1 copper_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~1 ~-1 copper_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~1 ~0 copper_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~1 ~1 copper_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~-1 ~-1 copper_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~-1 ~0 copper_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~-1 ~1 copper_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~0 ~-1 copper_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~0 ~0 copper_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~0 ~1 copper_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~1 ~-1 copper_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~1 ~0 copper_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~1 ~1 copper_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~-1 ~-1 copper_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~-1 ~0 copper_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~-1 ~1 copper_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~0 ~-1 copper_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~0 ~0 copper_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~0 ~1 copper_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~1 ~-1 copper_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~1 ~0 copper_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~1 ~1 copper_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="粗铜",type=item] at @s if block ~-1 ~-1 ~-1 copper_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~-1 ~0 copper_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~-1 ~1 copper_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~0 ~-1 copper_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~0 ~0 copper_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~0 ~1 copper_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~1 ~-1 copper_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~1 ~0 copper_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~1 ~1 copper_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~-1 ~-1 copper_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~-1 ~0 copper_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~-1 ~1 copper_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~0 ~-1 copper_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~0 ~0 copper_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~0 ~1 copper_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~1 ~-1 copper_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~1 ~0 copper_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~1 ~1 copper_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~-1 ~-1 copper_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~-1 ~0 copper_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~-1 ~1 copper_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~0 ~-1 copper_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~0 ~0 copper_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~0 ~1 copper_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~1 ~-1 copper_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~1 ~0 copper_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~1 ~1 copper_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_copper_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~-1 ~0 deepslate_copper_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~-1 ~1 deepslate_copper_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~0 ~-1 deepslate_copper_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~0 ~0 deepslate_copper_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~0 ~1 deepslate_copper_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~1 ~-1 deepslate_copper_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~1 ~0 deepslate_copper_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~-1 ~1 ~1 deepslate_copper_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~-1 ~-1 deepslate_copper_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~-1 ~0 deepslate_copper_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~-1 ~1 deepslate_copper_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~0 ~-1 deepslate_copper_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~0 ~0 deepslate_copper_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~0 ~1 deepslate_copper_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~1 ~-1 deepslate_copper_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~1 ~0 deepslate_copper_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~0 ~1 ~1 deepslate_copper_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~-1 ~-1 deepslate_copper_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~-1 ~0 deepslate_copper_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~-1 ~1 deepslate_copper_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~0 ~-1 deepslate_copper_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~0 ~0 deepslate_copper_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~0 ~1 deepslate_copper_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~1 ~-1 deepslate_copper_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~1 ~0 deepslate_copper_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="铜矿石",type=item] at @s if block ~1 ~1 ~1 deepslate_copper_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="粗铜",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_copper_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~-1 ~0 deepslate_copper_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~-1 ~1 deepslate_copper_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~0 ~-1 deepslate_copper_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~0 ~0 deepslate_copper_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~0 ~1 deepslate_copper_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~1 ~-1 deepslate_copper_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~1 ~0 deepslate_copper_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~-1 ~1 ~1 deepslate_copper_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~-1 ~-1 deepslate_copper_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~-1 ~0 deepslate_copper_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~-1 ~1 deepslate_copper_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~0 ~-1 deepslate_copper_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~0 ~0 deepslate_copper_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~0 ~1 deepslate_copper_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~1 ~-1 deepslate_copper_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~1 ~0 deepslate_copper_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~0 ~1 ~1 deepslate_copper_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~-1 ~-1 deepslate_copper_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~-1 ~0 deepslate_copper_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~-1 ~1 deepslate_copper_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~0 ~-1 deepslate_copper_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~0 ~0 deepslate_copper_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~0 ~1 deepslate_copper_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~1 ~-1 deepslate_copper_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~1 ~0 deepslate_copper_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="粗铜",type=item] at @s if block ~1 ~1 ~1 deepslate_copper_ore 0 run setblock ~1 ~1 ~1 air 0 destroy