#煤矿石

execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~-1 ~-1 coal_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~-1 ~0 coal_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~-1 ~1 coal_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~0 ~-1 coal_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~0 ~0 coal_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~0 ~1 coal_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~1 ~-1 coal_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~1 ~0 coal_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~1 ~1 coal_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~-1 ~-1 coal_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~-1 ~0 coal_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~-1 ~1 coal_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~0 ~-1 coal_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~0 ~0 coal_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~0 ~1 coal_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~1 ~-1 coal_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~1 ~0 coal_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~1 ~1 coal_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~-1 ~-1 coal_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~-1 ~0 coal_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~-1 ~1 coal_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~0 ~-1 coal_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~0 ~0 coal_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~0 ~1 coal_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~1 ~-1 coal_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~1 ~0 coal_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~1 ~1 coal_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~-1 ~-1 coal_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~-1 ~0 coal_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~-1 ~1 coal_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~0 ~-1 coal_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~0 ~0 coal_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~0 ~1 coal_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~1 ~-1 coal_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~1 ~0 coal_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~-1 ~1 ~1 coal_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~-1 ~-1 coal_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~-1 ~0 coal_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~-1 ~1 coal_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~0 ~-1 coal_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~0 ~0 coal_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~0 ~1 coal_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~1 ~-1 coal_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~1 ~0 coal_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~0 ~1 ~1 coal_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~-1 ~-1 coal_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~-1 ~0 coal_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~-1 ~1 coal_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~0 ~-1 coal_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~0 ~0 coal_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~0 ~1 coal_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~1 ~-1 coal_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~1 ~0 coal_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤矿石"] at @s if block ~1 ~1 ~1 coal_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~-1 ~-1 deepslate_coal_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~-1 ~0 deepslate_coal_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~-1 ~1 deepslate_coal_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~0 ~-1 deepslate_coal_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~0 ~0 deepslate_coal_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~0 ~1 deepslate_coal_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~1 ~-1 deepslate_coal_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~1 ~0 deepslate_coal_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~-1 ~1 ~1 deepslate_coal_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~-1 ~-1 deepslate_coal_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~-1 ~0 deepslate_coal_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~-1 ~1 deepslate_coal_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~0 ~-1 deepslate_coal_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~0 ~0 deepslate_coal_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~0 ~1 deepslate_coal_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~1 ~-1 deepslate_coal_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~1 ~0 deepslate_coal_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~0 ~1 ~1 deepslate_coal_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~-1 ~-1 deepslate_coal_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~-1 ~0 deepslate_coal_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~-1 ~1 deepslate_coal_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~0 ~-1 deepslate_coal_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~0 ~0 deepslate_coal_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~0 ~1 deepslate_coal_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~1 ~-1 deepslate_coal_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~1 ~0 deepslate_coal_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层煤矿石"] at @s if block ~1 ~1 ~1 deepslate_coal_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~-1 ~-1 deepslate_coal_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~-1 ~0 deepslate_coal_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~-1 ~1 deepslate_coal_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~0 ~-1 deepslate_coal_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~0 ~0 deepslate_coal_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~0 ~1 deepslate_coal_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~1 ~-1 deepslate_coal_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~1 ~0 deepslate_coal_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~-1 ~1 ~1 deepslate_coal_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~-1 ~-1 deepslate_coal_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~-1 ~0 deepslate_coal_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~-1 ~1 deepslate_coal_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~0 ~-1 deepslate_coal_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~0 ~0 deepslate_coal_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~0 ~1 deepslate_coal_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~1 ~-1 deepslate_coal_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~1 ~0 deepslate_coal_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~0 ~1 ~1 deepslate_coal_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~-1 ~-1 deepslate_coal_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~-1 ~0 deepslate_coal_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~-1 ~1 deepslate_coal_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~0 ~-1 deepslate_coal_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~0 ~0 deepslate_coal_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~0 ~1 deepslate_coal_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~1 ~-1 deepslate_coal_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~1 ~0 deepslate_coal_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="煤炭"] at @s if block ~1 ~1 ~1 deepslate_coal_ore run setblock ~1 ~1 ~1 air [] destroy