#钻石矿石

execute as @e[name="钻石",type=item] at @s if block ~-1 ~-1 ~-1 diamond_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~-1 ~0 diamond_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~-1 ~1 diamond_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~0 ~-1 diamond_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~0 ~0 diamond_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~0 ~1 diamond_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~1 ~-1 diamond_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~1 ~0 diamond_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~1 ~1 diamond_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~-1 ~-1 diamond_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~-1 ~0 diamond_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~-1 ~1 diamond_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~0 ~-1 diamond_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~0 ~0 diamond_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~0 ~1 diamond_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~1 ~-1 diamond_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~1 ~0 diamond_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~1 ~1 diamond_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~-1 ~-1 diamond_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~-1 ~0 diamond_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~-1 ~1 diamond_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~0 ~-1 diamond_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~0 ~0 diamond_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~0 ~1 diamond_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~1 ~-1 diamond_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~1 ~0 diamond_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~1 ~1 diamond_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~-1 ~-1 diamond_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~-1 ~0 diamond_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~-1 ~1 diamond_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~0 ~-1 diamond_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~0 ~0 diamond_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~0 ~1 diamond_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~1 ~-1 diamond_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~1 ~0 diamond_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~-1 ~1 ~1 diamond_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~-1 ~-1 diamond_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~-1 ~0 diamond_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~-1 ~1 diamond_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~0 ~-1 diamond_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~0 ~0 diamond_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~0 ~1 diamond_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~1 ~-1 diamond_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~1 ~0 diamond_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~0 ~1 ~1 diamond_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~-1 ~-1 diamond_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~-1 ~0 diamond_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~-1 ~1 diamond_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~0 ~-1 diamond_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~0 ~0 diamond_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~0 ~1 diamond_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~1 ~-1 diamond_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~1 ~0 diamond_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="钻石矿石",type=item] at @s if block ~1 ~1 ~1 diamond_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_diamond_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~-1 ~0 deepslate_diamond_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~-1 ~1 deepslate_diamond_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~0 ~-1 deepslate_diamond_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~0 ~0 deepslate_diamond_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~0 ~1 deepslate_diamond_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~1 ~-1 deepslate_diamond_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~1 ~0 deepslate_diamond_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~-1 ~1 ~1 deepslate_diamond_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~-1 ~-1 deepslate_diamond_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~-1 ~0 deepslate_diamond_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~-1 ~1 deepslate_diamond_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~0 ~-1 deepslate_diamond_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~0 ~0 deepslate_diamond_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~0 ~1 deepslate_diamond_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~1 ~-1 deepslate_diamond_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~1 ~0 deepslate_diamond_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~0 ~1 ~1 deepslate_diamond_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~-1 ~-1 deepslate_diamond_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~-1 ~0 deepslate_diamond_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~-1 ~1 deepslate_diamond_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~0 ~-1 deepslate_diamond_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~0 ~0 deepslate_diamond_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~0 ~1 deepslate_diamond_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~1 ~-1 deepslate_diamond_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~1 ~0 deepslate_diamond_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="深层钻石矿石",type=item] at @s if block ~1 ~1 ~1 deepslate_diamond_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="钻石",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_diamond_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~-1 ~0 deepslate_diamond_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~-1 ~1 deepslate_diamond_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~0 ~-1 deepslate_diamond_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~0 ~0 deepslate_diamond_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~0 ~1 deepslate_diamond_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~1 ~-1 deepslate_diamond_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~1 ~0 deepslate_diamond_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~-1 ~1 ~1 deepslate_diamond_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~-1 ~-1 deepslate_diamond_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~-1 ~0 deepslate_diamond_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~-1 ~1 deepslate_diamond_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~0 ~-1 deepslate_diamond_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~0 ~0 deepslate_diamond_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~0 ~1 deepslate_diamond_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~1 ~-1 deepslate_diamond_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~1 ~0 deepslate_diamond_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~0 ~1 ~1 deepslate_diamond_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~-1 ~-1 deepslate_diamond_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~-1 ~0 deepslate_diamond_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~-1 ~1 deepslate_diamond_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~0 ~-1 deepslate_diamond_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~0 ~0 deepslate_diamond_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~0 ~1 deepslate_diamond_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~1 ~-1 deepslate_diamond_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~1 ~0 deepslate_diamond_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="钻石",type=item] at @s if block ~1 ~1 ~1 deepslate_diamond_ore 0 run setblock ~1 ~1 ~1 air 0 destroy