#绿宝石矿石

execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~-1 ~-1 emerald_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~-1 ~0 emerald_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~-1 ~1 emerald_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~0 ~-1 emerald_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~0 ~0 emerald_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~0 ~1 emerald_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~1 ~-1 emerald_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~1 ~0 emerald_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~1 ~1 emerald_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~-1 ~-1 emerald_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~-1 ~0 emerald_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~-1 ~1 emerald_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~0 ~-1 emerald_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~0 ~0 emerald_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~0 ~1 emerald_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~1 ~-1 emerald_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~1 ~0 emerald_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~1 ~1 emerald_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~-1 ~-1 emerald_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~-1 ~0 emerald_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~-1 ~1 emerald_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~0 ~-1 emerald_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~0 ~0 emerald_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~0 ~1 emerald_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~1 ~-1 emerald_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~1 ~0 emerald_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~1 ~1 emerald_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~-1 ~-1 emerald_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~-1 ~0 emerald_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~-1 ~1 emerald_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~0 ~-1 emerald_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~0 ~0 emerald_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~0 ~1 emerald_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~1 ~-1 emerald_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~1 ~0 emerald_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~-1 ~1 ~1 emerald_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~-1 ~-1 emerald_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~-1 ~0 emerald_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~-1 ~1 emerald_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~0 ~-1 emerald_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~0 ~0 emerald_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~0 ~1 emerald_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~1 ~-1 emerald_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~1 ~0 emerald_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~0 ~1 ~1 emerald_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~-1 ~-1 emerald_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~-1 ~0 emerald_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~-1 ~1 emerald_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~0 ~-1 emerald_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~0 ~0 emerald_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~0 ~1 emerald_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~1 ~-1 emerald_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~1 ~0 emerald_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="绿宝石矿石",type=item] at @s if block ~1 ~1 ~1 emerald_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_emerald_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~-1 ~0 deepslate_emerald_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~-1 ~1 deepslate_emerald_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~0 ~-1 deepslate_emerald_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~0 ~0 deepslate_emerald_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~0 ~1 deepslate_emerald_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~1 ~-1 deepslate_emerald_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~1 ~0 deepslate_emerald_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~-1 ~1 ~1 deepslate_emerald_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~-1 ~-1 deepslate_emerald_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~-1 ~0 deepslate_emerald_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~-1 ~1 deepslate_emerald_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~0 ~-1 deepslate_emerald_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~0 ~0 deepslate_emerald_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~0 ~1 deepslate_emerald_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~1 ~-1 deepslate_emerald_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~1 ~0 deepslate_emerald_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~0 ~1 ~1 deepslate_emerald_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~-1 ~-1 deepslate_emerald_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~-1 ~0 deepslate_emerald_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~-1 ~1 deepslate_emerald_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~0 ~-1 deepslate_emerald_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~0 ~0 deepslate_emerald_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~0 ~1 deepslate_emerald_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~1 ~-1 deepslate_emerald_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~1 ~0 deepslate_emerald_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="深层绿宝石矿石",type=item] at @s if block ~1 ~1 ~1 deepslate_emerald_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_emerald_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~-1 ~0 deepslate_emerald_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~-1 ~1 deepslate_emerald_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~0 ~-1 deepslate_emerald_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~0 ~0 deepslate_emerald_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~0 ~1 deepslate_emerald_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~1 ~-1 deepslate_emerald_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~1 ~0 deepslate_emerald_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~-1 ~1 ~1 deepslate_emerald_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~-1 ~-1 deepslate_emerald_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~-1 ~0 deepslate_emerald_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~-1 ~1 deepslate_emerald_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~0 ~-1 deepslate_emerald_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~0 ~0 deepslate_emerald_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~0 ~1 deepslate_emerald_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~1 ~-1 deepslate_emerald_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~1 ~0 deepslate_emerald_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~0 ~1 ~1 deepslate_emerald_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~-1 ~-1 deepslate_emerald_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~-1 ~0 deepslate_emerald_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~-1 ~1 deepslate_emerald_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~0 ~-1 deepslate_emerald_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~0 ~0 deepslate_emerald_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~0 ~1 deepslate_emerald_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~1 ~-1 deepslate_emerald_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~1 ~0 deepslate_emerald_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="绿宝石",type=item] at @s if block ~1 ~1 ~1 deepslate_emerald_ore run setblock ~1 ~1 ~1 air [] destroy