#荧石粉-萤石粉

execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~-1 ~-1 glowstone run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~-1 ~0 glowstone run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~-1 ~1 glowstone run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~0 ~-1 glowstone run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~0 ~0 glowstone run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~0 ~1 glowstone run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~1 ~-1 glowstone run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~1 ~0 glowstone run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~1 ~1 glowstone run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~-1 ~-1 glowstone run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~-1 ~0 glowstone run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~-1 ~1 glowstone run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~0 ~-1 glowstone run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~0 ~0 glowstone run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~0 ~1 glowstone run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~1 ~-1 glowstone run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~1 ~0 glowstone run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~1 ~1 glowstone run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~-1 ~-1 glowstone run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~-1 ~0 glowstone run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~-1 ~1 glowstone run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~0 ~-1 glowstone run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~0 ~0 glowstone run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~0 ~1 glowstone run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~1 ~-1 glowstone run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~1 ~0 glowstone run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~1 ~1 glowstone run setblock ~1 ~1 ~1 air [] destroy

execute as @e[name="荧石",type=item] at @s if block ~-1 ~-1 ~-1 glowstone run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~-1 ~0 glowstone run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~-1 ~1 glowstone run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~0 ~-1 glowstone run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~0 ~0 glowstone run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~0 ~1 glowstone run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~1 ~-1 glowstone run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~1 ~0 glowstone run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~1 ~1 glowstone run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~-1 ~-1 glowstone run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~-1 ~0 glowstone run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~-1 ~1 glowstone run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~0 ~-1 glowstone run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~0 ~0 glowstone run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~0 ~1 glowstone run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~1 ~-1 glowstone run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~1 ~0 glowstone run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~1 ~1 glowstone run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~-1 ~-1 glowstone run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~-1 ~0 glowstone run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~-1 ~1 glowstone run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~0 ~-1 glowstone run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~0 ~0 glowstone run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~0 ~1 glowstone run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~1 ~-1 glowstone run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~1 ~0 glowstone run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~1 ~1 glowstone run setblock ~1 ~1 ~1 air [] destroy