#镀金黑石

execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~-1 ~-1 gilded_blackstone run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~-1 ~0 gilded_blackstone run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~-1 ~1 gilded_blackstone run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~0 ~-1 gilded_blackstone run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~0 ~0 gilded_blackstone run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~0 ~1 gilded_blackstone run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~1 ~-1 gilded_blackstone run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~1 ~0 gilded_blackstone run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~-1 ~1 ~1 gilded_blackstone run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~-1 ~-1 gilded_blackstone run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~-1 ~0 gilded_blackstone run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~-1 ~1 gilded_blackstone run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~0 ~-1 gilded_blackstone run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~0 ~0 gilded_blackstone run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~0 ~1 gilded_blackstone run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~1 ~-1 gilded_blackstone run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~1 ~0 gilded_blackstone run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~0 ~1 ~1 gilded_blackstone run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~-1 ~-1 gilded_blackstone run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~-1 ~0 gilded_blackstone run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~-1 ~1 gilded_blackstone run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~0 ~-1 gilded_blackstone run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~0 ~0 gilded_blackstone run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~0 ~1 gilded_blackstone run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~1 ~-1 gilded_blackstone run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~1 ~0 gilded_blackstone run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="镀金黑石",type=item] at @s if block ~1 ~1 ~1 gilded_blackstone run setblock ~1 ~1 ~1 air [] destroy