#粗金

execute as @e[name="粗金",type=item] at @s if block ~-1 ~-1 ~-1 gold_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~-1 ~0 gold_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~-1 ~1 gold_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~0 ~-1 gold_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~0 ~0 gold_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~0 ~1 gold_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~1 ~-1 gold_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~1 ~0 gold_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~1 ~1 gold_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~-1 ~-1 gold_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~-1 ~0 gold_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~-1 ~1 gold_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~0 ~-1 gold_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~0 ~0 gold_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~0 ~1 gold_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~1 ~-1 gold_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~1 ~0 gold_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~1 ~1 gold_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~-1 ~-1 gold_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~-1 ~0 gold_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~-1 ~1 gold_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~0 ~-1 gold_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~0 ~0 gold_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~0 ~1 gold_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~1 ~-1 gold_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~1 ~0 gold_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~1 ~1 gold_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

#金矿石

execute as @e[name="金矿石",type=item] at @s if block ~-1 ~-1 ~-1 gold_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~-1 ~0 gold_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~-1 ~1 gold_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~0 ~-1 gold_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~0 ~0 gold_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~0 ~1 gold_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~1 ~-1 gold_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~1 ~0 gold_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~1 ~1 gold_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~-1 ~-1 gold_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~-1 ~0 gold_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~-1 ~1 gold_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~0 ~-1 gold_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~0 ~0 gold_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~0 ~1 gold_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~1 ~-1 gold_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~1 ~0 gold_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~1 ~1 gold_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~-1 ~-1 gold_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~-1 ~0 gold_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~-1 ~1 gold_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~0 ~-1 gold_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~0 ~0 gold_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~0 ~1 gold_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~1 ~-1 gold_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~1 ~0 gold_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~1 ~1 gold_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

#粗金

execute as @e[name="粗金",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_gold_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~-1 ~0 deepslate_gold_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~-1 ~1 deepslate_gold_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~0 ~-1 deepslate_gold_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~0 ~0 deepslate_gold_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~0 ~1 deepslate_gold_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~1 ~-1 deepslate_gold_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~1 ~0 deepslate_gold_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~-1 ~1 ~1 deepslate_gold_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~-1 ~-1 deepslate_gold_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~-1 ~0 deepslate_gold_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~-1 ~1 deepslate_gold_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~0 ~-1 deepslate_gold_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~0 ~0 deepslate_gold_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~0 ~1 deepslate_gold_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~1 ~-1 deepslate_gold_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~1 ~0 deepslate_gold_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~0 ~1 ~1 deepslate_gold_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~-1 ~-1 deepslate_gold_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~-1 ~0 deepslate_gold_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~-1 ~1 deepslate_gold_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~0 ~-1 deepslate_gold_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~0 ~0 deepslate_gold_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~0 ~1 deepslate_gold_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~1 ~-1 deepslate_gold_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~1 ~0 deepslate_gold_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="粗金",type=item] at @s if block ~1 ~1 ~1 deepslate_gold_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

#金矿石

execute as @e[name="金矿石",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_gold_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~-1 ~0 deepslate_gold_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~-1 ~1 deepslate_gold_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~0 ~-1 deepslate_gold_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~0 ~0 deepslate_gold_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~0 ~1 deepslate_gold_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~1 ~-1 deepslate_gold_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~1 ~0 deepslate_gold_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~-1 ~1 ~1 deepslate_gold_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~-1 ~-1 deepslate_gold_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~-1 ~0 deepslate_gold_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~-1 ~1 deepslate_gold_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~0 ~-1 deepslate_gold_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~0 ~0 deepslate_gold_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~0 ~1 deepslate_gold_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~1 ~-1 deepslate_gold_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~1 ~0 deepslate_gold_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~0 ~1 ~1 deepslate_gold_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~-1 ~-1 deepslate_gold_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~-1 ~0 deepslate_gold_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~-1 ~1 deepslate_gold_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~0 ~-1 deepslate_gold_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~0 ~0 deepslate_gold_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~0 ~1 deepslate_gold_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~1 ~-1 deepslate_gold_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~1 ~0 deepslate_gold_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="金矿石",type=item] at @s if block ~1 ~1 ~1 deepslate_gold_ore 0 run setblock ~1 ~1 ~1 air 0 destroy