#荧石粉-萤石粉

execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~-1 ~-1 glowstone 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~-1 ~0 glowstone 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~-1 ~1 glowstone 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~0 ~-1 glowstone 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~0 ~0 glowstone 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~0 ~1 glowstone 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~1 ~-1 glowstone 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~1 ~0 glowstone 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~-1 ~1 ~1 glowstone 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~-1 ~-1 glowstone 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~-1 ~0 glowstone 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~-1 ~1 glowstone 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~0 ~-1 glowstone 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~0 ~0 glowstone 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~0 ~1 glowstone 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~1 ~-1 glowstone 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~1 ~0 glowstone 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~0 ~1 ~1 glowstone 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~-1 ~-1 glowstone 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~-1 ~0 glowstone 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~-1 ~1 glowstone 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~0 ~-1 glowstone 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~0 ~0 glowstone 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~0 ~1 glowstone 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~1 ~-1 glowstone 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~1 ~0 glowstone 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="荧石粉",type=item] at @s if block ~1 ~1 ~1 glowstone 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="荧石",type=item] at @s if block ~-1 ~-1 ~-1 glowstone 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~-1 ~0 glowstone 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~-1 ~1 glowstone 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~0 ~-1 glowstone 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~0 ~0 glowstone 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~0 ~1 glowstone 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~1 ~-1 glowstone 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~1 ~0 glowstone 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~-1 ~1 ~1 glowstone 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~-1 ~-1 glowstone 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~-1 ~0 glowstone 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~-1 ~1 glowstone 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~0 ~-1 glowstone 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~0 ~0 glowstone 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~0 ~1 glowstone 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~1 ~-1 glowstone 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~1 ~0 glowstone 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~0 ~1 ~1 glowstone 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~-1 ~-1 glowstone 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~-1 ~0 glowstone 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~-1 ~1 glowstone 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~0 ~-1 glowstone 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~0 ~0 glowstone 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~0 ~1 glowstone 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~1 ~-1 glowstone 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~1 ~0 glowstone 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="荧石",type=item] at @s if block ~1 ~1 ~1 glowstone 0 run setblock ~1 ~1 ~1 air 0 destroy