#青金石矿石

execute as @e[name="青金石",type=item] at @s if block ~-1 ~-1 ~-1 lapis_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~-1 ~0 lapis_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~-1 ~1 lapis_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~0 ~-1 lapis_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~0 ~0 lapis_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~0 ~1 lapis_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~1 ~-1 lapis_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~1 ~0 lapis_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~1 ~1 lapis_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~-1 ~-1 lapis_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~-1 ~0 lapis_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~-1 ~1 lapis_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~0 ~-1 lapis_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~0 ~0 lapis_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~0 ~1 lapis_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~1 ~-1 lapis_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~1 ~0 lapis_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~1 ~1 lapis_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~-1 ~-1 lapis_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~-1 ~0 lapis_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~-1 ~1 lapis_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~0 ~-1 lapis_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~0 ~0 lapis_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~0 ~1 lapis_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~1 ~-1 lapis_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~1 ~0 lapis_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~1 ~1 lapis_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~-1 ~-1 lapis_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~-1 ~0 lapis_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~-1 ~1 lapis_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~0 ~-1 lapis_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~0 ~0 lapis_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~0 ~1 lapis_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~1 ~-1 lapis_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~1 ~0 lapis_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~-1 ~1 ~1 lapis_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~-1 ~-1 lapis_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~-1 ~0 lapis_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~-1 ~1 lapis_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~0 ~-1 lapis_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~0 ~0 lapis_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~0 ~1 lapis_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~1 ~-1 lapis_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~1 ~0 lapis_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~0 ~1 ~1 lapis_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~-1 ~-1 lapis_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~-1 ~0 lapis_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~-1 ~1 lapis_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~0 ~-1 lapis_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~0 ~0 lapis_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~0 ~1 lapis_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~1 ~-1 lapis_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~1 ~0 lapis_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="青金石矿石",type=item] at @s if block ~1 ~1 ~1 lapis_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_lapis_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~-1 ~0 deepslate_lapis_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~-1 ~1 deepslate_lapis_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~0 ~-1 deepslate_lapis_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~0 ~0 deepslate_lapis_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~0 ~1 deepslate_lapis_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~1 ~-1 deepslate_lapis_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~1 ~0 deepslate_lapis_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~-1 ~1 ~1 deepslate_lapis_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~-1 ~-1 deepslate_lapis_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~-1 ~0 deepslate_lapis_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~-1 ~1 deepslate_lapis_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~0 ~-1 deepslate_lapis_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~0 ~0 deepslate_lapis_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~0 ~1 deepslate_lapis_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~1 ~-1 deepslate_lapis_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~1 ~0 deepslate_lapis_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~0 ~1 ~1 deepslate_lapis_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~-1 ~-1 deepslate_lapis_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~-1 ~0 deepslate_lapis_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~-1 ~1 deepslate_lapis_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~0 ~-1 deepslate_lapis_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~0 ~0 deepslate_lapis_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~0 ~1 deepslate_lapis_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~1 ~-1 deepslate_lapis_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~1 ~0 deepslate_lapis_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="深层青金石矿石",type=item] at @s if block ~1 ~1 ~1 deepslate_lapis_ore 0 run setblock ~1 ~1 ~1 air 0 destroy

execute as @e[name="青金石",type=item] at @s if block ~-1 ~-1 ~-1 deepslate_lapis_ore 0 run setblock ~-1 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~-1 ~0 deepslate_lapis_ore 0 run setblock ~-1 ~-1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~-1 ~1 deepslate_lapis_ore 0 run setblock ~-1 ~-1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~0 ~-1 deepslate_lapis_ore 0 run setblock ~-1 ~0 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~0 ~0 deepslate_lapis_ore 0 run setblock ~-1 ~0 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~0 ~1 deepslate_lapis_ore 0 run setblock ~-1 ~0 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~1 ~-1 deepslate_lapis_ore 0 run setblock ~-1 ~1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~1 ~0 deepslate_lapis_ore 0 run setblock ~-1 ~1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~-1 ~1 ~1 deepslate_lapis_ore 0 run setblock ~-1 ~1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~-1 ~-1 deepslate_lapis_ore 0 run setblock ~0 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~-1 ~0 deepslate_lapis_ore 0 run setblock ~0 ~-1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~-1 ~1 deepslate_lapis_ore 0 run setblock ~0 ~-1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~0 ~-1 deepslate_lapis_ore 0 run setblock ~0 ~0 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~0 ~0 deepslate_lapis_ore 0 run setblock ~0 ~0 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~0 ~1 deepslate_lapis_ore 0 run setblock ~0 ~0 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~1 ~-1 deepslate_lapis_ore 0 run setblock ~0 ~1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~1 ~0 deepslate_lapis_ore 0 run setblock ~0 ~1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~0 ~1 ~1 deepslate_lapis_ore 0 run setblock ~0 ~1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~-1 ~-1 deepslate_lapis_ore 0 run setblock ~1 ~-1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~-1 ~0 deepslate_lapis_ore 0 run setblock ~1 ~-1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~-1 ~1 deepslate_lapis_ore 0 run setblock ~1 ~-1 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~0 ~-1 deepslate_lapis_ore 0 run setblock ~1 ~0 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~0 ~0 deepslate_lapis_ore 0 run setblock ~1 ~0 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~0 ~1 deepslate_lapis_ore 0 run setblock ~1 ~0 ~1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~1 ~-1 deepslate_lapis_ore 0 run setblock ~1 ~1 ~-1 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~1 ~0 deepslate_lapis_ore 0 run setblock ~1 ~1 ~0 air 0 destroy
execute as @e[name="青金石",type=item] at @s if block ~1 ~1 ~1 deepslate_lapis_ore 0 run setblock ~1 ~1 ~1 air 0 destroy