#地狱石英-下界石英

execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~-1 ~-1 quartz_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~-1 ~0 quartz_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~-1 ~1 quartz_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~0 ~-1 quartz_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~0 ~0 quartz_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~0 ~1 quartz_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~1 ~-1 quartz_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~1 ~0 quartz_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~-1 ~1 ~1 quartz_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~-1 ~-1 quartz_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~-1 ~0 quartz_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~-1 ~1 quartz_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~0 ~-1 quartz_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~0 ~0 quartz_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~0 ~1 quartz_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~1 ~-1 quartz_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~1 ~0 quartz_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~0 ~1 ~1 quartz_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~-1 ~-1 quartz_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~-1 ~0 quartz_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~-1 ~1 quartz_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~0 ~-1 quartz_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~0 ~0 quartz_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~0 ~1 quartz_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~1 ~-1 quartz_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~1 ~0 quartz_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="地狱石英",type=item] at @s if block ~1 ~1 ~1 quartz_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~-1 ~-1 quartz_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~-1 ~0 quartz_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~-1 ~1 quartz_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~0 ~-1 quartz_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~0 ~0 quartz_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~0 ~1 quartz_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~1 ~-1 quartz_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~1 ~0 quartz_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~-1 ~1 ~1 quartz_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~-1 ~-1 quartz_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~-1 ~0 quartz_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~-1 ~1 quartz_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~0 ~-1 quartz_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~0 ~0 quartz_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~0 ~1 quartz_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~1 ~-1 quartz_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~1 ~0 quartz_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~0 ~1 ~1 quartz_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~-1 ~-1 quartz_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~-1 ~0 quartz_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~-1 ~1 quartz_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~0 ~-1 quartz_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~0 ~0 quartz_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~0 ~1 quartz_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~1 ~-1 quartz_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~1 ~0 quartz_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="地狱石英矿石",type=item] at @s if block ~1 ~1 ~1 quartz_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[name="下界石英",type=item] at @s if block ~-1 ~-1 ~-1 quartz_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~-1 ~-1 ~0 quartz_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~-1 ~-1 ~1 quartz_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~-1 ~0 ~-1 quartz_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~-1 ~0 ~0 quartz_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~-1 ~0 ~1 quartz_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~-1 ~1 ~-1 quartz_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~-1 ~1 ~0 quartz_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~-1 ~1 ~1 quartz_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~-1 ~-1 quartz_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~-1 ~0 quartz_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~-1 ~1 quartz_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~0 ~-1 quartz_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~0 ~0 quartz_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~0 ~1 quartz_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~1 ~-1 quartz_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~1 ~0 quartz_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~0 ~1 ~1 quartz_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~-1 ~-1 quartz_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~-1 ~0 quartz_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~-1 ~1 quartz_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~0 ~-1 quartz_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~0 ~0 quartz_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~0 ~1 quartz_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~1 ~-1 quartz_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~1 ~0 quartz_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="下界石英",type=item] at @s if block ~1 ~1 ~1 quartz_ore run setblock ~1 ~1 ~1 air [] destroy

execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~-1 ~-1 quartz_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~-1 ~0 quartz_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~-1 ~1 quartz_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~0 ~-1 quartz_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~0 ~0 quartz_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~0 ~1 quartz_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~1 ~-1 quartz_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~1 ~0 quartz_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~-1 ~1 ~1 quartz_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~-1 ~-1 quartz_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~-1 ~0 quartz_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~-1 ~1 quartz_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~0 ~-1 quartz_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~0 ~0 quartz_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~0 ~1 quartz_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~1 ~-1 quartz_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~1 ~0 quartz_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~0 ~1 ~1 quartz_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~-1 ~-1 quartz_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~-1 ~0 quartz_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~-1 ~1 quartz_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~0 ~-1 quartz_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~0 ~0 quartz_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~0 ~1 quartz_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~1 ~-1 quartz_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~1 ~0 quartz_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[name="下界石英矿石",type=item] at @s if block ~1 ~1 ~1 quartz_ore run setblock ~1 ~1 ~1 air [] destroy