#红石破坏
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~-1 redstone_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~0 redstone_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~1 redstone_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~-1 redstone_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~0 redstone_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~1 redstone_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~-1 redstone_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~0 redstone_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~1 redstone_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~-1 redstone_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~0 redstone_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~1 redstone_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~-1 redstone_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~0 redstone_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~1 redstone_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~-1 redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~0 redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~1 redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~-1 redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~0 redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~1 redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~-1 redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~0 redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~1 redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~-1 redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~0 redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~1 redstone_ore run setblock ~1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~-1 lit_redstone_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~0 lit_redstone_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~1 lit_redstone_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~-1 lit_redstone_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~0 lit_redstone_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~1 lit_redstone_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~-1 lit_redstone_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~0 lit_redstone_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~1 lit_redstone_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~-1 lit_redstone_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~0 lit_redstone_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~1 lit_redstone_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~-1 lit_redstone_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~0 lit_redstone_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~1 lit_redstone_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~-1 lit_redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~0 lit_redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~1 lit_redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~-1 lit_redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~0 lit_redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~1 lit_redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~-1 lit_redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~0 lit_redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~1 lit_redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~-1 lit_redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~0 lit_redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~1 lit_redstone_ore run setblock ~1 ~1 ~1 air [] destroy

#用红石矿石破坏
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~-1 ~-1 redstone_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~-1 ~0 redstone_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~-1 ~1 redstone_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~0 ~-1 redstone_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~0 ~0 redstone_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~0 ~1 redstone_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~1 ~-1 redstone_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~1 ~0 redstone_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~1 ~1 redstone_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~-1 ~-1 redstone_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~-1 ~0 redstone_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~-1 ~1 redstone_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~0 ~-1 redstone_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~0 ~0 redstone_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~0 ~1 redstone_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~1 ~-1 redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~1 ~0 redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~1 ~1 redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~-1 ~-1 redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~-1 ~0 redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~-1 ~1 redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~0 ~-1 redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~0 ~0 redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~0 ~1 redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~1 ~-1 redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~1 ~0 redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~1 ~1 redstone_ore run setblock ~1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~-1 ~-1 lit_redstone_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~-1 ~0 lit_redstone_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~-1 ~1 lit_redstone_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~0 ~-1 lit_redstone_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~0 ~0 lit_redstone_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~0 ~1 lit_redstone_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~1 ~-1 lit_redstone_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~1 ~0 lit_redstone_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~-1 ~1 ~1 lit_redstone_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~-1 ~-1 lit_redstone_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~-1 ~0 lit_redstone_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~-1 ~1 lit_redstone_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~0 ~-1 lit_redstone_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~0 ~0 lit_redstone_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~0 ~1 lit_redstone_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~1 ~-1 lit_redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~1 ~0 lit_redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~0 ~1 ~1 lit_redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~-1 ~-1 lit_redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~-1 ~0 lit_redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~-1 ~1 lit_redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~0 ~-1 lit_redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~0 ~0 lit_redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~0 ~1 lit_redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~1 ~-1 lit_redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~1 ~0 lit_redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石矿石"] at @s if block ~1 ~1 ~1 lit_redstone_ore run setblock ~1 ~1 ~1 air [] destroy

#用红石破坏深层
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~-1 deepslate_redstone_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~0 deepslate_redstone_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~1 deepslate_redstone_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~-1 deepslate_redstone_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~0 deepslate_redstone_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~1 deepslate_redstone_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~-1 deepslate_redstone_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~0 deepslate_redstone_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~1 deepslate_redstone_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~-1 deepslate_redstone_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~0 deepslate_redstone_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~1 deepslate_redstone_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~-1 deepslate_redstone_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~0 deepslate_redstone_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~1 deepslate_redstone_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~-1 deepslate_redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~0 deepslate_redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~1 deepslate_redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~-1 deepslate_redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~0 deepslate_redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~1 deepslate_redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~-1 deepslate_redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~0 deepslate_redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~1 deepslate_redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~-1 deepslate_redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~0 deepslate_redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~1 deepslate_redstone_ore run setblock ~1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~-1 lit_deepslate_redstone_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~0 lit_deepslate_redstone_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~-1 ~1 lit_deepslate_redstone_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~-1 lit_deepslate_redstone_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~0 lit_deepslate_redstone_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~0 ~1 lit_deepslate_redstone_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~-1 lit_deepslate_redstone_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~0 lit_deepslate_redstone_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~-1 ~1 ~1 lit_deepslate_redstone_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~-1 lit_deepslate_redstone_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~0 lit_deepslate_redstone_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~-1 ~1 lit_deepslate_redstone_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~-1 lit_deepslate_redstone_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~0 lit_deepslate_redstone_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~0 ~1 lit_deepslate_redstone_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~-1 lit_deepslate_redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~0 lit_deepslate_redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~0 ~1 ~1 lit_deepslate_redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~-1 lit_deepslate_redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~0 lit_deepslate_redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~-1 ~1 lit_deepslate_redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~-1 lit_deepslate_redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~0 lit_deepslate_redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~0 ~1 lit_deepslate_redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~-1 lit_deepslate_redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~0 lit_deepslate_redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="红石"] at @s if block ~1 ~1 ~1 lit_deepslate_redstone_ore run setblock ~1 ~1 ~1 air [] destroy

#深层红石矿石破坏深层
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~-1 ~-1 deepslate_redstone_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~-1 ~0 deepslate_redstone_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~-1 ~1 deepslate_redstone_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~0 ~-1 deepslate_redstone_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~0 ~0 deepslate_redstone_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~0 ~1 deepslate_redstone_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~1 ~-1 deepslate_redstone_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~1 ~0 deepslate_redstone_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~1 ~1 deepslate_redstone_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~-1 ~-1 deepslate_redstone_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~-1 ~0 deepslate_redstone_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~-1 ~1 deepslate_redstone_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~0 ~-1 deepslate_redstone_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~0 ~0 deepslate_redstone_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~0 ~1 deepslate_redstone_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~-1 deepslate_redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~0 deepslate_redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~1 deepslate_redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~-1 deepslate_redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~0 deepslate_redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~1 deepslate_redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~-1 deepslate_redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~0 deepslate_redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~1 deepslate_redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~-1 deepslate_redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~0 deepslate_redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~1 deepslate_redstone_ore run setblock ~1 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~-1 deepslate_redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~0 deepslate_redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~1 deepslate_redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~-1 deepslate_redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~0 deepslate_redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~1 deepslate_redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~-1 deepslate_redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~0 deepslate_redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~1 deepslate_redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~-1 deepslate_redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~0 deepslate_redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~1 deepslate_redstone_ore run setblock ~1 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~-1 ~-1 lit_deepslate_redstone_ore run setblock ~-1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~-1 ~0 lit_deepslate_redstone_ore run setblock ~-1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~-1 ~1 lit_deepslate_redstone_ore run setblock ~-1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~0 ~-1 lit_deepslate_redstone_ore run setblock ~-1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~0 ~0 lit_deepslate_redstone_ore run setblock ~-1 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~0 ~1 lit_deepslate_redstone_ore run setblock ~-1 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~1 ~-1 lit_deepslate_redstone_ore run setblock ~-1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~1 ~0 lit_deepslate_redstone_ore run setblock ~-1 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~-1 ~1 ~1 lit_deepslate_redstone_ore run setblock ~-1 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~-1 ~-1 lit_deepslate_redstone_ore run setblock ~0 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~-1 ~0 lit_deepslate_redstone_ore run setblock ~0 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~-1 ~1 lit_deepslate_redstone_ore run setblock ~0 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~0 ~-1 lit_deepslate_redstone_ore run setblock ~0 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~0 ~0 lit_deepslate_redstone_ore run setblock ~0 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~0 ~1 lit_deepslate_redstone_ore run setblock ~0 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~-1 lit_deepslate_redstone_ore run setblock ~0 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~0 lit_deepslate_redstone_ore run setblock ~0 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~0 ~1 ~1 lit_deepslate_redstone_ore run setblock ~0 ~1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~-1 lit_deepslate_redstone_ore run setblock ~1 ~-1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~0 lit_deepslate_redstone_ore run setblock ~1 ~-1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~-1 ~1 lit_deepslate_redstone_ore run setblock ~1 ~-1 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~-1 lit_deepslate_redstone_ore run setblock ~1 ~0 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~0 lit_deepslate_redstone_ore run setblock ~1 ~0 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~0 ~1 lit_deepslate_redstone_ore run setblock ~1 ~0 ~1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~-1 lit_deepslate_redstone_ore run setblock ~1 ~1 ~-1 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~0 lit_deepslate_redstone_ore run setblock ~1 ~1 ~0 air [] destroy
execute as @e[type=item,name="深层红石矿石"] at @s if block ~1 ~1 ~1 lit_deepslate_redstone_ore run setblock ~1 ~1 ~1 air [] destroy
